theme: jekyll-theme-minimal
title: Nerv for pyRevit
description: This is an intro page for Nerv for pyRevit. Please contact loumengfan@gmail.com for any questions
logo: nerv_logo.png
show_downloads: true
